/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Tue Jun 19 14:33:52 2018. */

#include "gatewaypckts.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t METER_TCKT_DATA_fields[4] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, METER_TCKT_DATA, gwId, gwId, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, METER_TCKT_DATA, type, gwId, 0),
    PB_FIELD(  3, STRING  , REQUIRED, STATIC  , OTHER, METER_TCKT_DATA, dataBuf, type, 0),
    PB_LAST_FIELD
};

const pb_field_t XLOAD_SENSOR_DATA_fields[6] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, XLOAD_SENSOR_DATA, gwId, gwId, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, XLOAD_SENSOR_DATA, outage, gwId, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, XLOAD_SENSOR_DATA, vbat, outage, 0),
    PB_FIELD(  4, FLOAT   , REQUIRED, STATIC  , OTHER, XLOAD_SENSOR_DATA, temp, vbat, 0),
    PB_FIELD(  5, FLOAT   , REQUIRED, STATIC  , OTHER, XLOAD_SENSOR_DATA, sensor1, temp, 0),
    PB_LAST_FIELD
};

const pb_field_t GPS_DATA_fields[6] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, GPS_DATA, gwId, gwId, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, GPS_DATA, lat, gwId, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, GPS_DATA, lon, lat, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, GPS_DATA, alt, lon, 0),
    PB_FIELD(  5, BOOL    , REQUIRED, STATIC  , OTHER, GPS_DATA, status, alt, 0),
    PB_LAST_FIELD
};

const pb_field_t PW_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, PW, type, type, 0),
    PB_FIELD(  2, STRING  , REQUIRED, CALLBACK, OTHER, PW, data, type, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
